spring:
  resources:
    add-mappings: true
  datasource:
    url: jdbc:postgresql://localhost:5432/gishub
    username: gishub
    password: gishub
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: gishub
      client-secret: 123456
      authorized-grant-types: password, refresh_token
      scope: read,write